project_id = "bjiycnotxzinsxwhlhyz"

[functions.process-email-queue]
verify_jwt = true

[functions.send-transactional-email]
verify_jwt = false

[functions.preview-transactional-email]
verify_jwt = false

[functions.handle-email-unsubscribe]
verify_jwt = false

[functions.handle-email-suppression]
verify_jwt = false

[functions.meta-capi]
verify_jwt = false

[functions.update-subscription]
verify_jwt = false

[functions.create-portal]
verify_jwt = false

[functions.stripe-webhook]
verify_jwt = false

[functions.create-checkout]
verify_jwt = false

[functions.report-lead-usage]
verify_jwt = false